apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: cert-manager-chart
chartName: cert-manager
chartRepoUrl: https://charts.jetstack.io
chartVersion: v1.2.0
releaseName: cert-manager
releaseNamespace: cert-manager
extraArgs:
  - --debug
  - --set=global.leaderElection.namespace=cert-manager
  - --set=global.logLevel=6
  - --set=installCRDs=true
  - --set=enable-certificate-owner-ref=true
  - --set=clusterResourceNamespace=cert-manager
  - --set=podDnsPolicy="None"
  - --set=podDnsConfig.nameServers=1.1.1.1,podDnsConfig.nameServers+=8.8.8.8