apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

generatorOptions:
  disableNameSuffixHash: true

# generators:
#   - cert-manager-chart.yaml

helmChartInflationGenerator:
- chartName: cert-manager
  chartRepoUrl: https://charts.jetstack.io
  chartVersion: v1.2.0
  releaseName: cert-manager
  releaseNamespace: cert-manager
  values: overrides.yaml

resources:
  - namespace.yaml