apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: "cert-manager"

generatorOptions:
  disableNameSuffixHash: true

helmChartInflationGenerator:
- chartName: cert-manager
  chartRepoUrl: https://charts.jetstack.io
  chartVersion: v1.2.0
  releaseName: cert-manager
  releaseNamespace: cert-manager
  values: overrides.yaml

resources:
  - namespace.yaml